#!/usr/bin/python
import sys
if len(sys.argv)==1:
    print("getSifRels siffile1 siffile2 siffile3 ...")
else:
    for siffile in sys.argv[1:]:
        if not siffile.endswith(".sif"):
            print(siffile+": must be a sif file, skipping")
        else:
            rels=[]
            for edge in open(siffile,"rt").read().splitlines():
                if edge.count("\t")!=2:
                    print(siffile+"/"+edge+": must be a 3 columns tsv, skipping")
                else:
                    rel=edge.split("\t")[1]
                    if rel not in rels:
                        rels.append(rel)
            if len(rels)==0:
                print(siffile+": no relations, skipping")
            else:
                open(siffile.replace(".sif",".rel.txt"),"w").write("\n".join(rels)+"\n")
