#!/usr/bin/python
import sys
if len(sys.argv)==1:
    print("getSifNodes siffile1 siffile2 siffile3 ...")
else:
    for siffile in sys.argv[1:]:
        if not siffile.endswith(".sif"):
            print(siffile+": must be a sif file, skipping")
        else:
            nodes=[]
            for edge in open(siffile,"rt").read().splitlines():
                if edge.count("\t")!=2:
                    print(siffile+"/"+edge+": must be a 3 columns tsv, skipping")
                else:
                    edge=edge.split("\t")
                    for node in [edge[0],edge[2]]:
                        if node not in nodes:
                            nodes.append(node)
            if len(nodes)==0:
                print(siffile+": no nodes, skipping")
            else:
                open(siffile.replace(".sif",".node.txt"),"w").write("\n".join(nodes)+"\n")
