#!/usr/bin/python
import sys
if len(sys.argv)==1:
    print("sifCleaner siffile1 siffile2 siffile3 ...")
else:
    import subprocess
    for siffile in sys.argv[1:]:
        if not siffile.endswith(".sif"):
            print(siffile+": must be a sif file, skipping")
        else:
            sif=[]
            for edge in open(siffile,"rt").read().splitlines():
                if edge.count("\t")!=2:
                    print(siffile+"/"+edge+": must be a 3 columns tsv, skipping")
                elif edge not in sif:
                    sif.append(edge)
            if len(sif)==0:
                print(siffile+": empty after cleaning, should be deleted")
                subprocess.run(["/usr/bin/rm","-i",siffile])
            else:
                open(siffile,"w").write("\n".join(sif)+"\n")
