#!/usr/bin/python
import sys
if len(sys.argv)==1:
    print("sifDiff siffile1 siffile2 siffile3 ...")
else:
    import copy
    sifs={}
    for siffile in sys.argv[1:]:
        if not siffile.endswith(".sif"):
            print(siffile+": must be a sif file, skipping")
        else:
            filename=siffile.split("/")[-1]
            if filename in sifs.keys():
                quit("sifDiff: identical file names in sif files, quitting")
            else:
                sif=[]
                for edge in open(siffile,"rt").read().splitlines():
                    if edge.count("\t")!=2:
                        print(siffile+"/"+edge+": must be a 3 columns tsv, skipping")
                    elif edge not in sif:
                        sif.append(edge)
                if len(sif)==0:
                    print(siffile+": empty after reading, skipping")
                else:
                    sifs[filename]=copy.deepcopy(sif)
    if len(sifs.keys())<2:
        print("sifDiff: require at least 2 sif files non empty after reading, quitting")
    else:
        diff={}
        report=[]
        for sif1 in sifs.keys():
            diff[sif1]={}
            for sif2 in sifs.keys():
                if sif1!=sif2:
                    diff[sif1][sif2]=[]
                    for edge in sifs[sif1]:
                        if edge not in sifs[sif2]:
                            diff[sif1][sif2].append("    "+edge)
        for siffile in sifs.keys():
            report.append(siffile+": "+str(len(sifs[siffile]))+" edges")
        report.append("")
        for sif1 in diff.keys():
            for sif2 in diff[sif1].keys():
                n1=len(sifs[sif1])
                n2=len(sifs[sif2])
                ndiff=len(diff[sif1][sif2])
                report.append(sif1+" not in "+sif2+": "+str(ndiff)+" edges ("+str(round(100*ndiff/n1,3))+"%) identical: "+str((n1==n2) and (ndiff==0)))
        for sif1 in diff.keys():
            for sif2 in diff[sif1].keys():
                report.append("")
                report.append(sif1+" not in "+sif2+":")
                if len(diff[sif1][sif2])!=0:
                    report.append("\n".join(diff[sif1][sif2]))
        open(".".join(sifs.keys()).replace(".sif","")+".diff.txt","w").write("\n".join(report)+"\n")
